name: Update Branches

on:
  push:
    branches:
      - main

jobs:
  update-branches:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Update branches
        run: |
          # Substitua o nome do seu branch principal e dos branches que deseja atualizar
          MAIN_BRANCH="main"
          BRANCHES=("androidCalculator" "appleCalculator")

          # Atualiza cada branch
          for branch in "${BRANCHES[@]}"; do
            git checkout "$branch"
            git pull origin "$MAIN_BRANCH"
            git push origin "$branch"
          done
